// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderEmail  AuthProvider = "email"
	AuthProviderGoogle AuthProvider = "google"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider
	Valid        bool // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type Gender string

const (
	GenderMale           Gender = "male"
	GenderFemale         Gender = "female"
	GenderPreferNotToSay Gender = "prefer_not_to_say"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type Field struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type InterestArea struct {
	ID        int64
	UserID    int64
	FieldID   int64
	CreatedAt pgtype.Timestamp
}

type OtpVerification struct {
	ID        int64
	UserID    int64
	Code      string
	ExpiresAt pgtype.Timestamp
	Domain    pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type PaymentMethod struct {
	ID            int64
	UserID        int64
	Type          string
	Provider      pgtype.Text
	AccountName   pgtype.Text
	AccountNumber pgtype.Text
	PhoneNumber   pgtype.Text
	IsDefault     pgtype.Bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Permission struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Profile struct {
	ID          int64
	FirstName   pgtype.Text
	LastName    pgtype.Text
	DateOfBirth pgtype.Date
	Gender      NullGender
	University  pgtype.Text
	Faculty     pgtype.Text
	Location    pgtype.Text
	UserID      int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Role struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
	CreatedAt    pgtype.Timestamp
}

type Transaction struct {
	ID            int64
	Amount        pgtype.Numeric
	BalanceBefore pgtype.Numeric
	BalanceAfter  pgtype.Numeric
	Reference     pgtype.Text
	Status        pgtype.Text
	WalletID      pgtype.Int8
	Type          pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type User struct {
	ID            int64
	Email         string
	EmailVerified pgtype.Bool
	Password      pgtype.Text
	Role          string
	GoogleID      pgtype.Text
	AuthProvider  NullAuthProvider
	RefreshToken  pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type Wallet struct {
	ID        int64
	Balance   pgtype.Numeric
	UserID    int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
