// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otps.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :exec
INSERT INTO otp_verifications (user_id, code, expires_at, domain)
VALUES ($1, $2, $3, $4)
`

type CreateOTPParams struct {
	UserID    int64
	Code      string
	ExpiresAt pgtype.Timestamp
	Domain    pgtype.Text
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.Exec(ctx, createOTP,
		arg.UserID,
		arg.Code,
		arg.ExpiresAt,
		arg.Domain,
	)
	return err
}

const deleteOTP = `-- name: DeleteOTP :exec
DELETE FROM otp_verifications WHERE user_id = $1 AND domain = $2
`

type DeleteOTPParams struct {
	UserID int64
	Domain pgtype.Text
}

func (q *Queries) DeleteOTP(ctx context.Context, arg DeleteOTPParams) error {
	_, err := q.db.Exec(ctx, deleteOTP, arg.UserID, arg.Domain)
	return err
}

const getOTP = `-- name: GetOTP :one
SELECT code FROM otp_verifications
WHERE user_id = $1 AND domain = $2
ORDER BY created_at
LIMIT 1
`

type GetOTPParams struct {
	UserID int64
	Domain pgtype.Text
}

func (q *Queries) GetOTP(ctx context.Context, arg GetOTPParams) (string, error) {
	row := q.db.QueryRow(ctx, getOTP, arg.UserID, arg.Domain)
	var code string
	err := row.Scan(&code)
	return code, err
}
