// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_methods.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :exec
INSERT INTO payment_methods (user_id, type, provider, account_name, account_number, phone_number)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePaymentMethodParams struct {
	UserID        int64
	Type          string
	Provider      pgtype.Text
	AccountName   pgtype.Text
	AccountNumber pgtype.Text
	PhoneNumber   pgtype.Text
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) error {
	_, err := q.db.Exec(ctx, createPaymentMethod,
		arg.UserID,
		arg.Type,
		arg.Provider,
		arg.AccountName,
		arg.AccountNumber,
		arg.PhoneNumber,
	)
	return err
}
