// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package database

import (
	"context"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (user_id)
VALUES ($1)
`

func (q *Queries) CreateProfile(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createProfile, userID)
	return err
}
