// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chargeWallet = `-- name: ChargeWallet :one
UPDATE wallets
SET balance = balance - $1
WHERE user_id = $2 AND balance >= $1
RETURNING id, balance, user_id, created_at, updated_at
`

type ChargeWalletParams struct {
	Amount pgtype.Numeric
	UserID int64
}

func (q *Queries) ChargeWallet(ctx context.Context, arg ChargeWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, chargeWallet, arg.Amount, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (balance, user_id)
VALUES ($1, $2)
    RETURNING id, balance, user_id, created_at, updated_at
`

type CreateWalletParams struct {
	Balance pgtype.Numeric
	UserID  int64
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.Balance, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, balance, user_id, created_at, updated_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletWithTransactions = `-- name: GetWalletWithTransactions :many
SELECT
    w.id,
    w.user_id,
    w.balance,
    w.created_at,
    w.updated_at,
    t.id AS transaction_id,
    t.amount AS transaction_amount,
    t.balance_before AS transaction_balance_before,
    t.balance_after AS transaction_balance_after,
    t.reference AS transaction_reference,
    t.status AS transaction_status,
    t.wallet_id AS transaction_wallet_id,
    t.created_at AS transaction_created_at,
    t.updated_at AS transaction_updated_at
FROM wallets w
LEFT JOIN transactions t ON w.id = t.wallet_id
WHERE w.user_id = $1
ORDER BY t.created_at DESC
`

type GetWalletWithTransactionsRow struct {
	ID                       int64
	UserID                   int64
	Balance                  pgtype.Numeric
	CreatedAt                pgtype.Timestamp
	UpdatedAt                pgtype.Timestamp
	TransactionID            pgtype.Int8
	TransactionAmount        pgtype.Numeric
	TransactionBalanceBefore pgtype.Numeric
	TransactionBalanceAfter  pgtype.Numeric
	TransactionReference     pgtype.Text
	TransactionStatus        pgtype.Text
	TransactionWalletID      pgtype.Int8
	TransactionCreatedAt     pgtype.Timestamp
	TransactionUpdatedAt     pgtype.Timestamp
}

func (q *Queries) GetWalletWithTransactions(ctx context.Context, userID int64) ([]GetWalletWithTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getWalletWithTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWalletWithTransactionsRow
	for rows.Next() {
		var i GetWalletWithTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionID,
			&i.TransactionAmount,
			&i.TransactionBalanceBefore,
			&i.TransactionBalanceAfter,
			&i.TransactionReference,
			&i.TransactionStatus,
			&i.TransactionWalletID,
			&i.TransactionCreatedAt,
			&i.TransactionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topUpWallet = `-- name: TopUpWallet :one
UPDATE wallets
SET balance = balance + $1
WHERE user_id = $2
RETURNING id, balance, user_id, created_at, updated_at
`

type TopUpWalletParams struct {
	Amount pgtype.Numeric
	UserID int64
}

func (q *Queries) TopUpWallet(ctx context.Context, arg TopUpWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, topUpWallet, arg.Amount, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
