// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chargeWallet = `-- name: ChargeWallet :one
UPDATE wallets
SET balance = balance - $1
WHERE user_id = $2 AND balance >= $1
RETURNING id, balance, user_id, created_at, updated_at
`

type ChargeWalletParams struct {
	Amount pgtype.Numeric
	UserID int64
}

func (q *Queries) ChargeWallet(ctx context.Context, arg ChargeWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, chargeWallet, arg.Amount, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (balance, user_id)
VALUES ($1, $2)
    RETURNING id, balance, user_id, created_at, updated_at
`

type CreateWalletParams struct {
	Balance pgtype.Numeric
	UserID  int64
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.Balance, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, balance, user_id, created_at, updated_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const topUpWallet = `-- name: TopUpWallet :one
UPDATE wallets
SET balance = balance + $1
WHERE user_id = $2
RETURNING id, balance, user_id, created_at, updated_at
`

type TopUpWalletParams struct {
	Amount pgtype.Numeric
	UserID int64
}

func (q *Queries) TopUpWallet(ctx context.Context, arg TopUpWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, topUpWallet, arg.Amount, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
